version: 0.0

os: linux 

files:
  - source: "./out"
    destination: "/var/www/html"
    overwrite: true

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3000
      runas: root