version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files: 
    - public/**/*
    - src/**/*
    - server.js
    - package.json
    - scripts/**/*

post_build:
  commands:
    - npm start